[package]
name = "bbrs-circuit-builder"
version = "0.1.0"
edition = "2024"

[dependencies]
bbrs-ecc = { path = "../ecc" }
bbrs-numeric = { path = "../numeric" }
bbrs-crypto = { path = "../crypto" }
bbrs-relations = { path = "../relations" }
bbrs-honk = { path = "../honk" }

[dev-dependencies]
